# Generated by Django 4.1 on 2022-08-25 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('0', '남성'), ('1', '여성')], max_length=1),
        ),
    ]
