# Generated by Django 4.1 on 2022-08-25 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_user_real_user_alter_content_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='real_user',
            name='gender',
            field=models.CharField(blank=True, choices=[('0', '남성'), ('1', '여성')], max_length=1),
        ),
    ]
