# Generated by Django 4.1 on 2022-08-25 06:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_real_user_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['created']},
        ),
        migrations.RemoveField(
            model_name='content',
            name='head_line',
        ),
        migrations.AddField(
            model_name='content',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, help_text='제목을 입력하세요.', max_length=100),
            preserve_default=False,
        ),
    ]
