# Generated by Django 4.1 on 2022-08-25 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_content_options_remove_content_head_line_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='author',
        ),
    ]
